### ISSUE TITLE
Entrega producto 1- Natalia Gómez

### ISSUE THREAD

**Issue by enataliagomezm** [SIB-Colombia/migracion#10]
Buenos días:

Confirmo la entrega del Primer producto Cronograma, el cual esta ya actualizado. 

Feliz día.

**Comment by nestorjal** [comment]
Perfecto @enataliagomezm , gracias!

**Comment by nestorjal** [comment]
@vdean26 documentar.

**Comment by vdean26** [comment]
Revisado
