### ISSUE TITLE
Fichas antiguas de Insectos sin citas y referencias bliograficas

### ISSUE THREAD

**Issue by enataliagomezm** [SIB-Colombia/migracion#11]
Hola a todos:

Estuve revisando mis fichas de insectos que forman parte del concepto otros y he visto varios casos en donde en los textos que aparecen en las fichas no existe ni referencia ni cita bibliográfica. Intente buscar en Mendeley con el nombre de las especies pero no sale absolutamente nada relacionado con estas fichas. Que dedo hacer en este caso?

Ejemplo:
http://www.biodiversidad.co:3000/index.php/catalogo/2859

**Comment by nestorjal** [comment]
Lamentablemente esto sucede mucho, no podemos migrar al nuevo catálogo información sin citas ni referencias. 

Si no hay citas en el texto ni referencias en los elementos, se debe asumir que está vacía. 

Todas las fichas que se están actualizando tendrán un enlace al final que llevara al PDF de la ficha original, así que esta información no migrada será visible de alguna manera.

**Comment by enataliagomezm** [comment]
Vale, entonces se debe buscar información nueva verdad? y si es así que ponemos en los proveedores de contenido? y que hacemos con los créditos específicos que aparecen en dichas fichas?

**Comment by nestorjal** [comment]
Por favor consulta el [_issue_ #13](https://github.com/SIB-Colombia/migracion/issues/13)
