### ISSUE TITLE
Problemas con las referencias en el Editor

### ISSUE THREAD

**Issue by jojuleon** [SIB-Colombia/migracion#12]
Hola a todos!

Desde hace unos minutos el editor no me permite ingresar el archivo .bib generado en Mendeley. La sección "Referencias" no presenta ningún contenido.

 Saludos,
Julián

**Comment by jojuleon** [comment]
Ya se arregló! creo que fue algún problema de conexión, perdón.

**Comment by ghost** [comment]
Buenas noches, efectivamente hay un problema con la sección de Referencias en el botón Seleccionar  archivo (.bib). Está apareciendo en el side bar al dar clic en el ícono de "más". Adicionalmente la caja de atributos de nueva referencia no se puede cerrar fácilmente.
![image](https://cloud.githubusercontent.com/assets/7794970/13098422/5b7c9b2e-d4f7-11e5-8b7c-cfb59a15ff3a.png)
![image](https://cloud.githubusercontent.com/assets/7794970/13098399/31f0b182-d4f7-11e5-9ca0-14fe222bc852.png)

Esperamos solucionar mañana a primera este problema. @mcubillos @vdean26

**Comment by nestorjal** [comment]
@leobuitrago ya hubo avances?

**Comment by ghost** [comment]
@nestorjal estamos sumando este con otros cambios que realizará el equipo de TI y serán subidos en bloque en lo que queda de la tarde.

**Comment by nestorjal** [comment]
Excelente, gracias!

**Comment by ghost** [comment]
Para agregar nuevas referencias, bien sea una por una, o a través de un archivo BibTeX (como realizan en este caso para el proceso la migración) se debe dar clic en el ícono "+".
![image](https://cloud.githubusercontent.com/assets/7794970/13193330/78c2308c-d744-11e5-8acd-838c1c290610.png)

Posteriormente encontrarán el botón "Seleccionar archivo" para agregar el archivo BibTeX de su especie o taxón.
![image](https://cloud.githubusercontent.com/assets/7794970/13193386/79a3dfd6-d745-11e5-9145-f407f44be005.png)
