### ISSUE TITLE
Créditos específicos

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/migracion#15]
@jojuleon  @edgarestebanhc  @enataliagomezm @alexander086 @SIB-Colombia/ac-team 

Estimado equipo,

En las fichas a migrar encontrarán algunas que contienen los siguientes el elementos :

**Créditos específicos** 
**Información sobre los tipos**
**Otros recursos**

La manera de documentarlos es a través de la sección **Información adicional**

**Créditos específicos** e **Información sobre los tipos** deben ser ingresados en el campo *_Más información *_ incluyendo los títulos de los elementos (ver imagen).

**Otros recursos** deben ser ingresados en el campo Enlaces (páginas web y multimedia.

A continuación un ejemplo:

![image](https://cloud.githubusercontent.com/assets/13892476/13117820/7742f7d6-d56f-11e5-9acc-545a6009037b.png)

**Comment by edgarestebanhc** [comment]
Hola a todos, muchas gracias por la info. En el caso de las fichas que ya se migraron y tenían esos elementos ¿que hay que hacer? Devolverse y agregar esa info en todas las fichas o dejarlas así e implementar los cambios en las fichas que se hagan a partir de este momento.

Saludos

**Comment by edgarestebanhc** [comment]
Lo pregunto porque ya se han hecho bastantes fichas y devolverse sería poco productivo.

Pero quedo atento

**Comment by vdean26** [comment]
Si, es necesario que se devuelvan.

**Comment by alexander086** [comment]
Ok Valerie muchas gracias
