### ISSUE TITLE
Dudas de fichas

### ISSUE THREAD

**Issue by jojuleon** [SIB-Colombia/migracion#17]
Buenas tardes,

Tengo un par de dudas con algunas fichas. 

1) Tengo la ficha de Canis lupus familiaris ("nueva" y dentro de la categoría de las spp. I3N) y la de Canis lupus ("antigua"), sin embargo la información que contiene esta última ficha hace referencia al perro doméstico cuando si somos estrictos debería hablar del lobo. ¿Dado que ya hay una ficha acerca del perro domestico qué hago con la ficha de Canis lupus ("antigua")? ¿Ingreso la información que esta o cambio totalmente la información de la ficha?.

2) La ficha de Dasypus novemcinctus no tiene proveedor de contenidos, En la base de datos sale como "ninguno".¿Qué hago en este caso?.

Saludos.

**Comment by nestorjal** [comment]
@vdean26  @leobuitrago 
1. Ciertamente hay un error, en la ficha _Canis lupus_ la información no es correcta, gracias por el aviso. Por favor ajusta la información, tal vez sea raro hacer una ficha de del lobo en el CBC pero seguro que hay un par por ahí (el que encontraron en Antioquia) o como los hipopótamos de Napoles.
2. En este caso puntual el proveedor de contenido es el IAvH.

**Comment by nestorjal** [comment]
Listo Julián, todas sus fichas ya tienen **Proveedor de contenido**.
