### ISSUE TITLE
Problema con sección Información Adicional

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#18]
Hola a todos, teniendo en cuenta que hay que añadir información en la sección de información adicional, al momento de ingresar datos en el campo de "Mas Información" si no se incluyen datos en los "Enlaces" al momento de guardar no queda guardado. Es decir si en la sección de información adicional no se incluye enlace, la información no queda guardada.

Que hacer en este caso ya que hay muchas fichas a las que hay que agregarle información en esta sección.

Saludos

**Comment by vdean26** [comment]
Hola,
Tienes toda la razón mañana a primera hora hablo con @mcubillos para que nos ayude a visualizar a través de la tabla, toda la información que está siendo ingresada.

**Comment by nestorjal** [comment]
@vdean26 algún avance?

**Comment by vdean26** [comment]
Este y otros cambios menores se han realizado con éxito y estan cargados en el editor desde está tarde. Esperamos que sean de ayuda en su proceso. 

Quedo atenta a cualquier pregunta.
