### ISSUE TITLE
Desaparición botón Guardar Ficha

### ISSUE THREAD

**Issue by enataliagomezm** [SIB-Colombia/migracion#20]
Hola:

Desapareció el botón Guardar Ficha del Editor....... @leobuitrago @vdean26 @nestorjal

**Comment by vdean26** [comment]
Hola @enataliagomezm Natalia y equipo @jojuleon @alexander086 @edgarestebanhc 
No desapareció. Está en la parte superior junto al botón Home. Es un cambio que terminamos de mejorar hoy. Tienen un botón guardar ficha y otro para salir a la página de inicio en cada sección. Sin embargo, recuerden que deben seguir haciendo click en el botón **Guardar** de cada elemento que lo tenga antes de Guardar la ficha.

Saludos!

![image](https://cloud.githubusercontent.com/assets/13892476/13188942/81336f14-d722-11e5-9ede-4aa9a818311c.png)

**Comment by enataliagomezm** [comment]
Hola Valerie:

En la versión que tengo abierta del Editor no aparece por ningún lado el botón que señalas en la imagen.

**Comment by ghost** [comment]
Esto sucedió temporalmente mientras reiniciábamos el servidor para actualizar los cambios y mejoras en el editor. Como menciona Valerie, ahora tendrán siempre presente en la parte superior derecha del editor los botones:

**Guardar ficha**
![image](https://cloud.githubusercontent.com/assets/7794970/13192924/109eca4c-d73f-11e5-9d9c-10ec00418777.png)

**Inicio**
![image](https://cloud.githubusercontent.com/assets/7794970/13193044/a3fb03e0-d740-11e5-89c3-f8d59e2307e7.png)

Este cambio permitirá mejorar la navegación dentro del editor e igualmente permite no tener que ir siempre a la sección "Información Adicional" para guardar los cambios de la ficha. Sin embargo, recuerden que deben seguir haciendo clic en el botón _Guardar_ de cada elemento que lo tenga antes de Guardar la ficha.
