### ISSUE TITLE
IMPORTANTE EDITOR 

### ISSUE THREAD

**Issue by enataliagomezm** [SIB-Colombia/migracion#21]
Hola:

Desde hace 20 minutos el editor esta guardando varias versiones de las fichas que voy creando y almacenando. Por lo que veo, cada vez  que doy clic en el botón "Guardar" para almacenar la información migrada se crea una versión nueva de la ficha.

Quedo atenta a su respuesta.

Ejemplo:

![image](https://cloud.githubusercontent.com/assets/17183821/13193764/5e8379da-d74c-11e5-9392-cef91f36b540.png)

**Comment by ghost** [comment]
Revisando el editor efectivamente, cada vez que se presiona el icono de guardar ![image](https://cloud.githubusercontent.com/assets/7794970/13192924/109eca4c-d73f-11e5-9d9c-10ec00418777.png) el Editor está creando una nueva versión en el sistema. Por el momento les agradezco a todos que **solo presionen una vez este botón al finalizar la documentación de la ficha** mientras solucionamos este problema y que se le pueda dar "guardar" las veces que sea necesario sin que el editor genere otras versiones. Al parecer este error se produjo luego de los últimos ajustes realizados al Editor.

Agradezco su comprensión y paciencia.

@danipilze @mcubillos es importante dar solución a este issue lo mas pronto posible!! los contratistas están trabajando los fines de semana.

**Comment by ghost** [comment]
Según me comentan las personas de TI del SiB (que ya revisaron este problema) este error sólo se puede solucionar hasta el día lunes. Por ahora tienen dos posibles opciones para guardar sus fichas:
1. Como les comenté anteriormente, solo utilicen una vez el botón guardar al finalizar la documentación de la totalidad de la ficha.
2. Una vez creada la ficha con los datos básicos (ej. taxonomía, partes asociadas y referencias) den clic a guardar ficha y luego diríjanse al "inicio" del editor, la ubican en el listado y una vez entren pueden terminar de documentar y usar el botón de guardar ficha las veces que lo requieran. De este modo el editor no creará más versiones, sino que guardará sobre la misma ficha creada inicialmente.

Espero haya claridad al respecto y nos aseguraremos que desde TI solucionen este problema a primera hora del lunes. Agradecemos el reporte de fallas (issues) que han mantenido hasta el momento, no duden en informar cualquier novedad.

Saludos
