### ISSUE TITLE
Ficha creada no aparece en MAMUT

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#22]
Buenos días para todos, 

Realicé la ficha de la especie "Phyllomedusa venusta" pero al buscarla en la lista de fichas en MAMUT ésta no aparece, afortunadamente pude guardar el link a la ficha creada: [http://mamut.biodiversidad.co/edit?id=56c801faf0106c67230e7428].
Considero que es un punto que debe verificarse ya que si no hubiera guardado el link hubiera perdido la ficha.

Saludos

Edgar Herrera

**Comment by vdean26** [comment]
Buenos dias,

Revisando el problema encontré que efectivamente estamos presentando inconsitencias en el buscador.  Es posible acceder a tus fichas @edgarestebanhc y a las de Natalia @enataliagomezm escribiendo en el buscador su segundo apellido (Collazos y Melendro respectivamente) para solucionar esto necesitaremos ayuda del equipo de TI. Por ahora espero que les funcione buscando por su segundo apellido, de lo contrario me cuentan a ver como puedo ayudarlos. 

![screen shot 2016-02-20 at 10 34 32](https://cloud.githubusercontent.com/assets/13892476/13197534/6d83f06e-d7be-11e5-9947-cb76be948e0a.png)

![screen shot 2016-02-20 at 10 34 49](https://cloud.githubusercontent.com/assets/13892476/13197537/7474dd5c-d7be-11e5-9596-0463c867d89e.png)

Saludos!
