### ISSUE TITLE
Botón automático Licencia Atribución - No Comercial - Compartir igual (CC BY-NC-SA 4.0)

### ISSUE THREAD

**Issue by alexander086** [SIB-Colombia/migracion#23]
Buenas noches compañeros. Realizando una ficha me di cuenta que en algunas ocasiones, la elección automático de la  Licencia Atribución - No Comercial - Compartir igual (CC BY-NC-SA 4.0) no se encontraba elegida, por lo tanto procedía a marcarla, entonces por favor estén pendientes por cualquier cosa evitar obviarla. Leonardo y Valerie por favor puede decirle al equipo de informatica que si pueden revisar esto. Muchas gracias y buenas noches

**Comment by ghost** [comment]
Ok Alex, gracias por el reporte. Sería importante para nosotros detectar exactamente cuales son los elementos que presentan este problema, así que les agradezco comentarnos cuáles son los que presentan este caso.

**Comment by alexander086** [comment]
Vale Leo, voy a anotar cuáles son y los reporto. Saludos

**Comment by alexander086** [comment]
Buenas noches compañero. Hasta ahora me he dado cuenta que este inconveniente se ha dado en el campo Descripción General en Alimentación. en el transcurso de la migración les diré en donde ás encuentro este inconveniente. Saludos

**Comment by edgarestebanhc** [comment]
Hola a Todos, a mi no me pasa eso en Alimentación sino en Reproducción. Pero me di cuenta que a pesar de no aparacer 'visualmente' seleccionada la casilla (⬤), ésta sí esta 'activa' ya que al dejarla como está, la licencia sí aparece después.

![image](https://cloud.githubusercontent.com/assets/11566815/13209913/c7085fa0-d8f7-11e5-95a3-38419cc6d99f.png)

Saludos a todos,

EH

**Comment by alexander086** [comment]
ok, gracias Edgar
