### ISSUE TITLE
Reinicio de servidor

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/migracion#25]
Hola a todos, por favor dejar de trabajar un momento mientras reiniciamos el servidor, para que no pierdan su trabajo.

En un momento les avisamos.

**Comment by enataliagomezm** [comment]
Buenos días:

Vale. Sin embargo, quisiera pedirles el enorme favor que cuando vayan a realizar estos cambios en el servidor o en editor nos avisen con tiempo para poder suspender nuestras actividades mientras ustedes realizan los ajustes. Debido a que en mi caso he perdido el trabajo realizado mientras ustedes desarrollan los cambios pertinentes en el editor. 

Agradezco mucho su comprensión.

Saludos.

**Comment by jojuleon** [comment]
Buenos días,

Ya se reinicio el editor? se puede trabajar sin problema?

Julián

**Comment by ghost** [comment]
No, en unos minutos. Les pedimos un poco de paciencia, mientras subimos varios ajustes que el editor requiere.

**Comment by ghost** [comment]
Hola a todos, estamos aún haciendo ajustes adicionales pero ya se han arreglado varios de los inconvenientes que venimos presentando desde el viernes con el editor. Por ahora pueden serguir trabajando pero les pido tengan en cuenta:
1. Filtrar sus fichas solo por apellido (ej "Gómez", "León")
2. Ya se puede buscar también en el "Inicio" por el nombre del taxón (ej. Chironius monticola)
3. El orden de las fichas en el inicio cambió. Ahora se muestra inicialmente la creada mas recientemente
   ![image](https://cloud.githubusercontent.com/assets/7794970/13226748/2ab4cfa2-d961-11e5-877a-7977feff0e7a.png)
4. Se cambió el color del botón de inicio para que se diferencie del de Guardar ficha. 
   ![image](https://cloud.githubusercontent.com/assets/7794970/13226561/fb3f7d18-d95f-11e5-8a0e-5c052d56907c.png)
   Ya probamos y en teoría no debe crear duplicados de fichas independientemente de que lo presionen varias veces. Agradezco prueben esta opción y nos comenten.
5. Ya se puede observar cada ficha por "Fecha de creación" (Fecha y Hora), sin embargo aún estamos realizando algunos ajustes para que también aparezca este dato cuando se aplica algún filtro en el Inicio (por ejemplo por "Creador").

Volveremos a reiniciar el servidor en horas de la tarde (les avisaremos con tiempo) una vez ajustemos lo que se encuentra pendiente. Agradezco su paciencia y espero nos informen cualquier novedad frente a los últimos cambios realizados al editor.
