### ISSUE TITLE
Información de ejemplares de colección

### ISSUE THREAD

**Issue by alexander086** [SIB-Colombia/migracion#27]
Buenos días compañeros. Una pregunta para Leonardo y Valerie. En el caso que en las fichas antiguas exista información de ejemplares de colección, ¿dónde se puede relacionar esa información en el editor? no encuentro ningún campo que se me acomode. Muchas gracias por la respuesta. Saludos

**Comment by vdean26** [comment]
Hola Alex, por favor revisa el issue: Créditos específicos #15. En el encontrarás el procedimiento para documentar información de ejemplares de colección y otra información adicional.

Saludos
