### ISSUE TITLE
Proveedor de contenido único

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#3]
Buenas noches para todos, 

En la sección de proveedor de contenidos (PC), como ya sabemos, se despliega una lista de la que debemos escoger al PC de la ficha respectiva.

Ya que cada lista tiene un PC único, sería posible que al escoger un PC de la lista desplegable, éste quede activado para toda la ficha y no tener que seleccionarlo en cada sección.

Saludos!

Edgar H

**Comment by ghost** [comment]
Hola Edgar,

Teniendo presente que cada ficha se compone de varios elementos y cada elemento podrá ser aportado por un PC diferente (supongamos: _ABO_\- Hábitat; _Calidris_\- Comportamiento; _Conservación Internacional_ - Usos); no se piensa en el nuevo Catálogo que las fichas tengan un solo PC, por lo tanto no se puede activar uno solo para toda la ficha. Es decir, que por ahora, aunque resulte tedioso se debe escoger el PC en cada elemento migrado al Editor.

Saludos

**Comment by edgarestebanhc** [comment]
Muchas gracias Leonardo, ya entiendo.
