### ISSUE TITLE
Problemas editor

### ISSUE THREAD

**Issue by jojuleon** [SIB-Colombia/migracion#33]
Buenas tardes,

La sección de "Usos, Manejo y Conservación" del editor no permite guarda la información ingresada. Tampoco permite cargar las referencias ni el proveedor de contenidos. Muchas de las especies de plantas tienen el elemento "usos", así que es urgente solucionar este inconveniente.

Julián

**Comment by ghost** [comment]
Hola Julián, si parece que hay un problema con este elemento, y lo está revisando el equipo de TI. Te pido que por ahora marques en tu archivo excel (google) las fichas que requieren documentar este elemento y lo dejes como "pendiente" mientras resolvemos este inconveniente.

Saludos,

**Comment by ghost** [comment]
@jojuleon @edgarestebanhc @enataliagomezm @alexander086 Vamos a reiniciar el servidor para resolver este issue por favor hagan una pausa de 15 minutos en el uso del editor.

Gracias!

**Comment by ghost** [comment]
Error solucionado! @jojuleon por favor revisar el editor.

**Comment by jojuleon** [comment]
Ya quedo sirviendo.

Gracias!
