### ISSUE TITLE
Fichas Duplicadas

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/migracion#37]
Buenos días a todos,

Luego del error que se produjo hace unos días en el editor con el botón guardar quedaron algunas fichas duplicadas en el sistema. Por favor revisen el siguiente archivo de [Fichas Duplicadas](https://docs.google.com/spreadsheets/d/1tASAvKlgxTQ3YkjHmu7QXASxS6yc8FpZIjsbbKERCLA/edit?usp=sharing) y marquen con una "X" la(s) que se debe(n) eliminar, de acuerdo a la que consideren como la última versión; obviamente la que no marquen será la única que no se elimine. Por favor responder a este issue una vez realicen la tarea.

Mil gracias!

@alexander086 no tiene fichas duplicadas.

**Comment by edgarestebanhc** [comment]
Hola a todos, 

Ya puse la información solicitada en el archivo excel.

Saludos, 

EEHC

**Comment by ghost** [comment]
Gracias Edgar,

quedo pendiente de @jojuleon.

**Comment by jojuleon** [comment]
Buenas tardes,

El archivo de Excel que me aparece solo es de lectura y por lo tanto no me deja hacer ninguna modificación.

El archivo duplicado a eliminar corresponde al siguiente link:
http://mamut.biodiversidad.co/edit?id=56c94a46f0106c67230e743e

Saludos,
Julián

**Comment by ghost** [comment]
Perfecto Julián,

Sí, lo siento no te había habilitado la edición del archivo. Pero ya queda claro con el enlace que envías teniendo en cuenta que solo tenías esa duplicada.

Muchas gracias a todos!

**Comment by edgarestebanhc** [comment]
Hola Leo, 

Respecto a los duplicados, acabé de crear otros! Lo siento mucho:

Especie: Diasporus gularis

Definitivo: http://mamut.biodiversidad.co/edit?id=56d4af573c16479905cba8a6
Eliminar: http://mamut.biodiversidad.co/edit?id=56d4af573c16479905cba8a7
http://mamut.biodiversidad.co/edit?id=56d4af573c16479905cba8a8
http://mamut.biodiversidad.co/edit?id=56d4af573c16479905cba8a9

Mil disculpas!!!

**Comment by ghost** [comment]
Edgar y los demás,
1. Por favor si se vuelve a presentar este error pongan esta información en el archivo [Fichas Duplicadas](https://docs.google.com/spreadsheets/d/1tASAvKlgxTQ3YkjHmu7QXASxS6yc8FpZIjsbbKERCLA/edit?usp=sharing) que les compartí para tal fin (ya habilité la edición para que lo puedan modificar), ya que es el documento que consultará el equipo de TI para borrar del sistema las fichas duplicadas por error.
2. Fue error tuyo o del Editor?, agradezco me confirmes.

Saludos!

**Comment by edgarestebanhc** [comment]
Hola Leo, fue error mio, al momento de crear la ficha no me salio el letrero que siempre sale 'Ficha creada exitosamente', razón por la cual le di click al botón guardar varias veces. Ya añadí la info al archivo.

Saludos
