### ISSUE TITLE
Especies repetidas

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#39]
Hola a todos, 

En la lista que tengo de anfibios aparecen dos especies repetidas con distinto nombre científico:
-Lithobates catesbeianus (válida)
-Rana catesbeiana (no válida)

Quisiera saber en este caso que debo hacer, o con cuál debo quedarme.

Saludos

**Comment by nestorjal** [comment]
Hola Edgar,

Ya eliminé del archivo la ficha _Rana catesbeiana_ ID:504.

Saludos,
