### ISSUE TITLE
Elementos no contemplados en el estándar

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#4]
Buenas noches, mi pregunta esta enfocada a todos aquellos elementos que no estén contemplados en el estándar y que no se puedan de una u otra forma "acomodar' a los elementos existentes. En dado caso, a demás de proponerlos en la plantilla (perfil), ¿incluimos o no  incluimos dichos elementos en las fichas (mamut)?

**Comment by ghost** [comment]
Puedes darnos un ejemplo claro por favor

**Comment by edgarestebanhc** [comment]
Hola Leo claro que si, son algunos casos como los siguientes:

Otros recursos en Internet:
www.iucnredlist.org/amphibians
http://research.amnh.org/herpetology/amphibia/
http://amphibiaweb.org/

Créditos específicos: Al Instituto Amazónico de Investigaciones Científicas Sinchi. Al Sistema de Información Ambiental Territorial de la Amazonia Colombiana SIAT-AC. La elaboración de esta ficha fue posible gracias al apoyo del gobierno de Finlandia a través del convenio entre la Secretaria General de la CAN y el Instituto Sinchi para el proyecto Sistema Regional Amazónico de Información Ambiental con énfasis en Biodiversidad de los países miembros de la CAN, (programa BIOCAN), componente SIAT-AC.

Información de tipos:  Holotipo: UTA A-4943, por designación original. Localidad Tipo: "Yapima, Rio Vaupés, Vaupés, Colombia. (69° 28´ W 1° 03´ N)".

**Comment by ghost** [comment]
Ya tengo idea de dónde podríamos "acomodarlos" o qué nuevos elementos deberíamos incluir en el [editor](mamut.biodiversidad.co), pero quiero socializarlo primero con el equipo del SIB; espero responderte mañana mismo. Agradezco mucho tus "issues" o dudas ya que esto es lo que nos permite detectar falencias en el editor que no habíamos contemplado y espero podamos solucionar de manera inmediata, o bien pensar en una manera de incorporar esta información mas adelante.

Buenas noches

**Comment by nestorjal** [comment]
@leobuitrago tenemos algún avance?

**Comment by ghost** [comment]
@nestorjal estamos sumando este con otros cambios que realizará el equipo de TI y serán subidos en bloque en lo que queda de la tarde.

**Comment by ghost** [comment]
Para resolver el inconveniente que reportó @edgarestebanhc dispusimos en la sección Información adicional los siguientes campos:
![image](https://cloud.githubusercontent.com/assets/7794970/13193465/dd6c439a-d746-11e5-8b93-bf0dd174dbf3.png)

De este modo, cuando necesite documentar:

_Otros recursos en Internet_ emplee el atributo **Enlaces (páginas web y multimedia)**
- En **Fuente** escriba la URL principal de la página web
- Si tiene la **Referencia** de la página documente.
- Seleccione el Proveedor de contenido.
  ![image](https://cloud.githubusercontent.com/assets/7794970/13193952/33f42440-d750-11e5-9f91-4c1aab685425.png)
- Dar clic al botón inferior "Guardar" cada vez que se ingresa un enlace adicional con su respectiva información.

_Créditos específicos_ e _Información de tipos_ emplee el elemento **Más información**

![image](https://cloud.githubusercontent.com/assets/7794970/13193957/4540546c-d750-11e5-9872-ef0d8cffb690.png)
- Idealmente documente y Guarde el elemento **Mas información** luego de llenar y "Guardar" el atributo **Enlaces (páginas web y multimedia)**

**Comment by edgarestebanhc** [comment]
@leobuitrago Muchas gracias!
