### ISSUE TITLE
Fichas sin Proveedor de Contenido

### ISSUE THREAD

**Issue by enataliagomezm** [SIB-Colombia/migracion#40]
Buenas Noches:

Estaba mirando mi archivo de Excel correspondiente a las fichas de insectos y tengo 104 fichas sin proveedor de contenido. Quisiera pedirles que por favor me ayuden a completar esta información para poder desarrollar la migración de estas al editor.

Quedo atenta a su respuesta.

Saludos,

Natalia Gómez

**Comment by nestorjal** [comment]
Hola Natalia,

Disculpa la demora en actualizar esto. Ya el archivo esta listo.

Saludos.
