### ISSUE TITLE
Catálogo antiguo sin acceso

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#44]
Buenas tardes para todos, 

Resulta que al tratar de acceder al catálogo antiguo o al editor del catalogo antiguo (http://www.biodiversidad.co:3000/ & http://54.225.116.72/) obtengo los siguientes mensajes:

http://www.biodiversidad.co:3000/index.php/catalogo/282
![image](https://cloud.githubusercontent.com/assets/11566815/13446524/4ded5f34-dfe2-11e5-91d1-05b0f94767a7.png)

http://54.225.116.72/fichas/282
![image](https://cloud.githubusercontent.com/assets/11566815/13446532/5b257ea2-dfe2-11e5-82eb-58386f7779f9.png)

Quisiera saber si ya tienen conocimiento de esta situación ya que al no tener acceso a las fichas que hay que migrar la labor se retrasa tremendamente.

Saludos, 

Edgar H

**Comment by nestorjal** [comment]
@danipilze me puedes ayudar con esto por favor.

**Comment by nestorjal** [comment]
@valegrajales alguna idea para solucionar esto por el momento?

**Comment by nestorjal** [comment]
@edgarestebanhc intenta accediendo a la nueva dirección http://www.biodiversidad.co/fichas/282

Es una solución temporal, las fichas duplicadas no se podrán ver, pero por ahora es lo que tenemos. Haremos todo lo posible por solucionar esto rápidamente.

**Comment by edgarestebanhc** [comment]
Hola @nestorjal efectivamente, con éste si puedo entrar.

Gracias

**Comment by ghost** [comment]
@valegrajales necesitamos la nueva URL de acceso al Admin del CBC intermedio (originalmente http://www.biodiversidad.co:3000/) que cambió el día de ayer en el lanzamiento del catálogo 1.3.

Gracias

**Comment by valegrajales** [comment]
La nueva URL para acceso a editor es: http://54.225.116.72:3000/

**Comment by edgarestebanhc** [comment]
Hola a todos,

Probando la URL http://54.225.116.72:3000/fichas/5092 no me da acceso....

![image](https://cloud.githubusercontent.com/assets/11566815/13467004/67b7c5ac-e06a-11e5-8138-ffc2950f3579.png)

**Comment by ghost** [comment]
Hola a todos,

Ya se corrigió este inconveniente. La estructura de la dirección URL para las fichas en el editor viejo es (ej. para _Zenaida auriculata_) http://54.225.116.72:3000/index.php/catalogo/4155 y para la vista en el catálogo es http://www.biodiversidad.co/fichas/4155. Solo cambia el ID al final de la URL para cada ficha.

Ya actualicé las columnas **url_admin** y **url_cbc** en el archivo de cada uno en Google con estas nuevas direcciones para cada una de sus fichas, es decir que pueden volver a acceder solo dando clic en el enlace.

Saludos!
