### ISSUE TITLE
Provedor de contenido en fichas modificadas

### ISSUE THREAD

**Issue by enataliagomezm** [SIB-Colombia/migracion#48]
Hola:

Quería preguntarles si el proveedor de contenido cambia por el Equipo Coordinador Sib en las fichas, cuando la información de los items ha sido modificada (ej.. inclusión de fuentes bibliográficas, modificación de texto, etc.) o  se han agregado items (ej. inclusión de tipo de reproducción o descripción taxonómica).

Gracias y saludos

**Comment by ghost** [comment]
Hola,

Cuando ustedes agreguen cualquier elemento nuevo en una ficha o realicen una modificación en el contenido original, que haga de ese elemento una nueva versión, el proveedor de contenido será en ese caso **Equipo coordinador del SiB Colombia**.

Saludos

**Comment by alexander086** [comment]
Una pregunta, se supone que nosotros al migrar las fichas viejas las estamos modificando en la descripción general, es decir, se les esta poniendo por lo menos un elemento nuevo a todas las fichas, ¿eso cuenta para que el proveedor de contenido cambie?

**Comment by ghost** [comment]
La _**Descripción general**_, como saben, es un elemento que no contiene ni referencias, ni licencia ni proveedores de contenido por que es como un "Abstract" del taxón o del contenido de la ficha, así que si ese es el elemento nuevo que agregan no deben preocuparse por poner un Proveedor de contenido como tal. El resto de elementos que tenga la ficha originalmente documentados (ej. Distribución, Nombres Comunes, etc.) debe tener el proveedor de contenido correspondiente del archivo Google.

Si el elemento que agregan como nuevo es cualquier otro que permita incluir Proveedor de contenido (ej. "Hábitat"), en ese caso el proveedor de contenido si será **Equipo coordinador del SiB Colombia**.
