### ISSUE TITLE
Mendeley no funciona

### ISSUE THREAD

**Issue by alexander086** [SIB-Colombia/migracion#54]
Buenos días compañeros. Me encuentro en un apuro. Estaba trabajando normalmente en Mendeley, cuando de un momento a otro se salio del sistema. Mendeley me pidió validarme de nuevo y esta vez me dejo ver el siguiente ítem  
![image](https://cloud.githubusercontent.com/assets/17283600/13702289/747c2a42-e75b-11e5-932f-d411e5e09f53.png).

Al principio pensé que era mi internet, pero éste esta funcionado bien. Luego volví a descargar la versión de mendeley desktop y sigue apareciendo el mismo aviso cuando intento validarme. Me pueden ayudar o es un problema mio?

Muchas gracias y saludos

**Comment by alexander086** [comment]
Compañeros, buenos días. Mendeley ya funciona nuevamente. Disculpas por los agravios. Buen dìa

**Comment by ghost** [comment]
Alguien más presenta este problema?  Agradezco nos informen para saber si es un problema de la conexión del equipo de Alex o de la cuenta del SiB en Mendeley.
