### ISSUE TITLE
Nombres comunes atomizados - Editor

### ISSUE THREAD

**Issue by ghost** [SIB-Colombia/migracion#6]
@enataliagomezm @edgarestebanhc @jojuleon 
El elemento **Nombres comúnes atomizados** debe ser documentado en el [editor](mamut.biodiversidad.co)
![image](https://cloud.githubusercontent.com/assets/7794970/13032196/669720e8-d2b7-11e5-9193-0c2860f12909.png)

teniendo en cuenta también el listado de **Nombres comunes asignados a la ficha**  que se encuentra en las fichas del [url_admin](http://www.biodiversidad.co:3000/index.php/catalogo/index).
![image](https://cloud.githubusercontent.com/assets/7794970/13032200/8ad8cfec-d2b7-11e5-99e4-90aea6e21fbb.png)

**Comment by vdean26** [comment]
Esto es importante ya que en GIBF no se encuentran reportados los nombres comunes regionales y étnicos.

**Comment by edgarestebanhc** [comment]
Hola a todos, muchas gracias por la info, y en los casos que en la ficha del url_admin no se encuentre ningún nombre científico que se haría?

**Comment by vdean26** [comment]
Te refieres a nombres comunes? (por fa puedes escribir un nuevo issue con esta pregunta)
