### ISSUE TITLE
No funciona vista de editor

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#60]
Hola a todos, 

La vista de las fichas que se da por la siguiente dirección "http://54.225.116.72:3000/index.php/catalogo/488" no se puede acceder, no se si sea algo momentaneo, pero preferí notificar ya que lleva 30 min sin funcionar.

Saludos, 

EdgarH

**Comment by alexander086** [comment]
Buenas noches compañeros. Estoy en la misma situación que Edgar. Cualquier cosa estoy pendiente.

Saludos.

Alexander Trujillo

**Comment by ghost** [comment]
Hola a todos,

Parece que el daño de debe a una actualización que se realizó en algunos servidores el día de hoy, estoy informando del tema al equipo de Tecnologías de Información del SiB para que nos den una pronta solución. Por ahora les pido que continúen el proceso de migración con la URL_CBC de sus archivos (dominio www.biodiversidad.co).

Feliz noche!

**Comment by ghost** [comment]
Buenos días a todos,

El error ya fue solucionado por el equipo de TI. Pueden acceder a las url_admin de sus archivos.

Saludos!
