### ISSUE TITLE
Nombres comunes

### ISSUE THREAD

**Issue by edgarestebanhc** [SIB-Colombia/migracion#7]
Hola a todos, teniendo en cuenta los issues anteriores sobre la documentación de los nombres comunes me surge una pregunta:

En caso de que en la ficha del url_admin no haya ningún nombre común, ¿qué se haría?.

Saludos, 

EEHC

**Comment by vdean26** [comment]
En caso de que la ficha que se esté migrando no cuente con la información de un elemento (en este caso nombre común), simplemente ese elemento no se diligencia. Sin embargo, si la ficha ya posee descripción general y aún falta el elemento nuevo que deben agregar, puede llenar la información con sus respectivas referencias. 

*_NOTA IMPORTANTE: *_ Este elemento no necesita referencia
@jojuleon @edgarestebanhc @enataliagomezm
