### ISSUE TITLE
Entrega producto 1 - Julián León

### ISSUE THREAD

**Issue by jojuleon** [SIB-Colombia/migracion#9]
Hola a todos!

Confirmo la actualización de mi respectivo archivo para dar entrega del producto 1 (cronograma).

Saludos,

Julián León

**Comment by nestorjal** [comment]
Perfecto @jojuleon , gracias!

**Comment by nestorjal** [comment]
@vdean26 documentar.

**Comment by vdean26** [comment]
Revisado.
